export const API_URL = "http://.......";


export const REDUCER_ACTIONS = {
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_INIT: 'LOGIN_INIT',
    LOGIN_ERROR: 'LOGIN_ERROR',
    SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
    SIGNUP_INIT: 'SIGNUP_INIT',
    SIGNUP_ERROR: 'SIGNUP_ERROR',
    AUTO_LOGIN_SUCCESS: 'AUTO_LOGIN_SUCCESS',
    AUTO_SIGNUP_ERROR: 'AUTO_SIGNUP_ERROR',
    IS_CONNECTED: 'IS_CONNECTED',
    IS_CONNECTED_SUCCESS: 'IS_CONNECTED_SUCCESS',
    IS_CONNECTED_ERROR: 'IS_CONNECTED_ERROR',
    COUNTER_UPDATE: 'COUNTER_UPDATE',
}

export const COLOR = {
    BUTTON_COLOR: "#6B52AE"
}

export const IMAGES = {
    SIDE_BAR: require('../assets/Images/side.png')
}

